# Generated by Django 3.2.8 on 2025-05-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='ciudad',
            field=models.CharField(default='Bogotá', max_length=100),
            preserve_default=False,
        ),
    ]
